name: Run Python Script with Docker

on:
  push:

jobs:
  docker-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t test-image .

      - name: Run Docker container
        run: docker run --rm test-image

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to DockerHub
        run: |
          docker tag test-image ${{ secrets.DOCKER_USERNAME }}/test-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/test-image:latest
